name: Fanie Reynders
description: Code. Build. Blog.
meta_description: "Writing about technical stuffs"
paginate_path: "/blog/page:num/"
permalink: pretty 
markdown: redcarpet
excerpt_separator: <!--more-->
highlighter: pygments
logo: /assets/images/profile.png
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
twitter_username: FanieReynders
github_username: faniereynders
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://reynders.co'
author:         'Fanie Reynders'
